# Archivo de configuración para Netlify

[build]
  # Directorio donde están tus funciones de Netlify
  functions = "netlify/functions"

[functions]
  # Asegurarnos de que Node.js se use para construir las funciones
  node_bundler = "esbuild"
